# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3a317db51875368aceba7a38829c1d850078310cd536876f3fa2ebe8621e803373c00c12a106f8f4c26e5856c72f778425618e6609b0ac537f1960b7b644ec86

test:
  secret_key_base: c96971aeb75003b3045093152bdd07842e528f42f263262d5e541ac0947b6d4b4f045354d7fd3ae1dfc050afa7dab17e4d8c17fa9fb84cb588522f7bb1ebb04a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
